### PR TITLE
UI Screens

### PR DESCRIPTION
**Pull request by AnkurChunekar**
Added
- Horizontal Card component
- Watch Later, History, and Liked screens
-  implemented React Router to the project.

### CODE REVIEW

**Review by dipteekhd — APPROVED** [review]
Very Nice UI! Code looks fine!

**Comment by gadgetfather** [comment]
- Great UI 👍
- Just a small thing i noticed whenever I am clicking on your brand name , it is redirecting to your portfolio instead of homepage.
- self-explanatory class names

**Review by gadgetfather — APPROVED** [review]

**Comment by AnkurChunekar** [comment]
> 

This was by mistake, just to avoid the empty href error

**Comment by AnkurChunekar** [comment]
> * Great UI 👍
> * Just a small thing i noticed whenever I am clicking on your brand name , it is redirecting to your portfolio instead of homepage.
> * self-explanatory class names

This was by mistake, just to avoid the empty href error

**Pull request merged**
